export const apiDomain = 'http://localhost:8000/'
export const loginUrl = apiDomain + 'oauth/token'
export const userUrl = apiDomain + 'api/user'
export const forumGetAll = apiDomain + 'api/v1/forum'
export const forumAddUrl = apiDomain + 'api/v1/forum'
